name: biltekteknikservis
description: "Teknik servis uygulamasi"
publish_to: 'none'
version: 1.3.0+130

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  http: ^1.5.0
  provider: ^6.1.5+1
  universal_io: ^2.2.2
  device_info_plus: ^12.1.0
  package_info_plus: ^9.0.0
  android_id: ^0.4.0
  overlay_support: ^2.1.0
  flutter_ringtone_player: ^5.0.0-dev.1
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.2
  simple_barcode_scanner: ^0.3.0
  intl: any
  flutter_localizations:
    sdk: flutter
  share_plus: ^12.0.0
  flutter_contacts: ^1.1.9+2
  photo_view: ^0.15.0
  pro_image_editor: ^11.5.8
  image_picker: ^1.2.0
  mask_text_input_formatter: ^2.9.0
  google_fonts: ^6.3.2
  flutter_keyboard_visibility: ^6.0.0
  permission_handler: ^11.3.1
  firebase_core: ^4.1.1
  firebase_app_check: ^0.4.1
  firebase_messaging: ^16.0.2
  firebase_ai: ^3.3.0
  markdown_widget: ^2.3.2+8
  speech_to_text: 7.3.0
  encrypt: ^5.0.3
  local_auth: ^2.3.0
  local_auth_android: ^1.0.55
  local_auth_darwin: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - fonts/
    - images/
    - sounds/
